# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_podio', '0003_remove_aplicacion_nombre2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hook',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=32)),
                ('trigger', models.CharField(choices=[(b'item.create', b'item.create'), (b'item.update', b'item.update'), (b'item.delete', b'item.delete')], max_length=16)),
                ('hook_id', models.CharField(max_length=32)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_podio.Aplicacion')),
            ],
        ),
    ]
