# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_podio', '0004_hook'),
    ]

    operations = [
        migrations.AddField(
            model_name='hook',
            name='field',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
