# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_podio', '0005_hook_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='hook',
            name='uses',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name=b'N\xc3\xbamero de veces que ha sido usado este hook'),
        ),
    ]
