# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-01 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_podio', '0007_auto_20160327_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicacion',
            name='workspace',
            field=models.CharField(max_length=32, verbose_name='Espacio de trabajo al cual pertenece esta aplicaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='hook',
            name='uses',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='N\xfamero de veces que ha sido usado este hook'),
        ),
    ]
