# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-10 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_podio', '0012_auto_20160512_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hook',
            old_name='path',
            new_name='name',
        ),
    ]
